/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EduSys;

import DAO.NhanVienDAO;
import Entity.NhanVien;
import Untils.MsgBox;
import Untils.Xreport;
import java.awt.Color;

/**
 *
 * @author doanp
 */
public class IF_QuenMatKhau extends javax.swing.JInternalFrame {

    NhanVienDAO daoNV;

    /**
     * Creates new form IF_QuenMatKhau
     */
    public IF_QuenMatKhau() {
        initComponents();
        init();
    }

    void init() {
        setTitle("EduSys - Quên mật khẩu");
        setClosable(true);
        setDefaultCloseOperation(2);
        setMaximizable(true);
        setIconifiable(true);
        daoNV = new NhanVienDAO();
        clearForm();
    }

    void clearForm() {
        btnGui.setEnabled(false);
        txtMK1.setEditable(false);
        txtMK2.setEditable(false);
        btnThayDoi.setEnabled(false);
        btnXT.setEnabled(false);
        txtMa.setEnabled(false);
        txtMK1.setText("");
        txtMK2.setText("");
        txtMa.setText("");
        txtTenDN.setText("");
        lblTrangThai.setText(" ");
        lblTrangThai1.setText(" ");
        lblTrangThai2.setText(" ");
        lblTrangThai3.setText(" ");

    }

    void checkUser() {
        if (daoNV.selectById(txtTenDN.getText()) == null && txtTenDN.getText().length() > 0) {
            lblTrangThai.setText("Tên đăng nhập không tồn tại !!");
            lblTrangThai.setForeground(Color.RED);
            btnGui.setEnabled(false);
        } else if (daoNV.selectById(txtTenDN.getText()) != null) {
            lblTrangThai.setText("Nhấn \"Gửi mã\" để lấy mã xác thực");
            lblTrangThai.setForeground(Color.BLUE);
            btnGui.setEnabled(true);
        } else {
            lblTrangThai.setText(" ");
            btnGui.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTenDN = new javax.swing.JTextField();
        btnGui = new javax.swing.JButton();
        lblTrangThai = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        lblTrangThai1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMK1 = new javax.swing.JTextField();
        txtMK2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnThayDoi = new javax.swing.JButton();
        lblTrangThai2 = new javax.swing.JLabel();
        lblTrangThai3 = new javax.swing.JLabel();
        btnXT = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Quên mật khẩu? ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tên đăng nhập:");

        txtTenDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDNActionPerformed(evt);
            }
        });
        txtTenDN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenDNKeyReleased(evt);
            }
        });

        btnGui.setText("Gửi mã");
        btnGui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiActionPerformed(evt);
            }
        });

        lblTrangThai.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTrangThai.setText(" ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Mã xác thực:");

        txtMa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaKeyReleased(evt);
            }
        });

        lblTrangThai1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTrangThai1.setText(" ");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Thay đổi mật khẩu");

        jLabel5.setText("Mật khẩu mới:");

        txtMK1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMK1KeyReleased(evt);
            }
        });

        txtMK2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMK2KeyReleased(evt);
            }
        });

        jLabel6.setText("Xác nhận:");

        btnThayDoi.setText("Thay đổi mật khẩu");
        btnThayDoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThayDoiActionPerformed(evt);
            }
        });

        lblTrangThai2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTrangThai2.setText(" ");

        lblTrangThai3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTrangThai3.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMK2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMK1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTrangThai3)
                                    .addComponent(lblTrangThai2))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 138, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(109, 109, 109))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnThayDoi)
                                .addGap(143, 143, 143))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMK1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTrangThai3)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMK2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTrangThai2)
                .addGap(11, 11, 11)
                .addComponent(btnThayDoi)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btnXT.setText("Xác thực");
        btnXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTrangThai1)
                                    .addComponent(lblTrangThai)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtMa, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                            .addComponent(txtTenDN))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnGui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenDN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGui))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTrangThai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXT)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTrangThai1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int code;

    void Gui() {
        double random = Math.random();
        if (random < 0.1) {
            random += 0.1;
        }
        code = (int) Math.round(random * 1000000);
        Xreport.sendCode(code);
        lblTrangThai.setText(" ");
        lblTrangThai1.setText("Kiểm tra gmail và nhập mã xác thực tại đây");
        lblTrangThai1.setForeground(Color.BLUE);
        txtMa.setEnabled(true);
    }
    private void btnGuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiActionPerformed
        Gui();
    }//GEN-LAST:event_btnGuiActionPerformed

    private void txtTenDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDNActionPerformed

    }//GEN-LAST:event_txtTenDNActionPerformed

    private void txtTenDNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenDNKeyReleased
        checkUser();
    }//GEN-LAST:event_txtTenDNKeyReleased
    void xacThuc() {
        if (Integer.parseInt(txtMa.getText()) == code) {
            lblTrangThai1.setText(" ");
            MsgBox.alert(this, "Xác thực thành công vui lòng thay đổi mật khẩu");
            txtMK1.setEditable(true);
            txtMK2.setEditable(true);
            lblTrangThai3.setText("Nhập mật khẩu mới tại đây");
            lblTrangThai3.setForeground(Color.BLUE);
        } else {
            MsgBox.alert(this, "Mã xác thực không chính xác vui lòng kiểm tra lại !!");
        }
    }
    private void btnXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXTActionPerformed
        xacThuc();
    }//GEN-LAST:event_btnXTActionPerformed
    void checkPass() {
        int lengthPass = txtMK1.getText().length();
        if (lengthPass == 0) {
            lblTrangThai3.setText("Nhập mật khẩu mới tại đây");
            lblTrangThai3.setForeground(Color.BLUE);
        } else if (lengthPass < 3) {
            lblTrangThai3.setText("Mật khẩu yếu");
            lblTrangThai3.setForeground(Color.RED);
        } else if (lengthPass < 7) {
            lblTrangThai3.setText("Mật khẩu trung bình");
            lblTrangThai3.setForeground(Color.ORANGE);
        } else {
            lblTrangThai3.setText("Mật khẩu mạnh");
            lblTrangThai3.setForeground(Color.GREEN);
        }
    }

    void checkPass2() {
        if (txtMK1.getText().equalsIgnoreCase(txtMK2.getText()) && txtMK1.getText().length() > 0) {
            lblTrangThai2.setText("Mật khẩu xác nhận trùng khớp");
            lblTrangThai2.setForeground(Color.BLUE);
            btnThayDoi.setEnabled(true);
        } else {
            lblTrangThai2.setText("Mật khẩu xác nhận không trùng khớp hoặc ít hơn 1 ký tự!!");
            lblTrangThai2.setForeground(Color.RED);
            btnThayDoi.setEnabled(false);
        }
    }
    private void txtMaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaKeyReleased
        if (txtMa.getText().length() > 0) {
            btnXT.setEnabled(true);
        } else {
            btnXT.setEnabled(false);
        }
    }//GEN-LAST:event_txtMaKeyReleased

    private void txtMK1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMK1KeyReleased
        checkPass();
    }//GEN-LAST:event_txtMK1KeyReleased

    private void txtMK2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMK2KeyReleased
        checkPass2();
    }//GEN-LAST:event_txtMK2KeyReleased
    void thayDoi() {
            NhanVien nv = daoNV.selectById(txtTenDN.getText());
            nv.setMatKhau(txtMK2.getText());
            daoNV.update(nv);
    }
    private void btnThayDoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThayDoiActionPerformed
        try {
            thayDoi();
            MsgBox.alert(this, "Thay đổi mật khẩu thành công");
            clearForm();
        } catch (Exception e) {
            MsgBox.alert(this, "Đổi mật khẩu thất bại !!");
        }
    }//GEN-LAST:event_btnThayDoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGui;
    private javax.swing.JButton btnThayDoi;
    private javax.swing.JButton btnXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JLabel lblTrangThai1;
    private javax.swing.JLabel lblTrangThai2;
    private javax.swing.JLabel lblTrangThai3;
    private javax.swing.JTextField txtMK1;
    private javax.swing.JTextField txtMK2;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtTenDN;
    // End of variables declaration//GEN-END:variables
}
